dotnet/Autobarn.Website/Controllers/ManufacturersController.cs
using Autobarn.Data;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Autobarn.Website.Controllers {
	public class ManufacturersController : Controller {
		private readonly IAutobarnDatabase db;

		public ManufacturersController(IAutobarnDatabase db) {
			this.db = db;
		}
		public IActionResult Index() {
			var vehicles = db.ListManufacturers();
			return View(vehicles);
		}

		public IActionResult Models(string id) {
			var manufacturer = db.ListManufacturers().FirstOrDefault(m => m.Code == id);
			return View(manufacturer);
		}
	}
}

dotnet/Autobarn.Website/Controllers/ModelsController.cs
using Autobarn.Data;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Autobarn.Website.Controllers {
	public class ModelsController : Controller {
		private readonly IAutobarnDatabase db;

		public ModelsController(IAutobarnDatabase db) {
			this.db = db;
		}

		public IActionResult Vehicles(string id) {
			var model = db.ListModels().FirstOrDefault(m => m.Code == id);
			return View(model);
		}

		public IActionResult Index() {
			var models = db.ListModels();
			return View(models);
		}
	}
}

dotnet/Autobarn.Website/Controllers/VehiclesController.cs
using Autobarn.Data;
using Autobarn.Data.Entities;
using Autobarn.Website.Models;
using Microsoft.AspNetCore.Mvc;

namespace Autobarn.Website.Controllers {
	public class VehiclesController : Controller {
		private readonly IAutobarnDatabase db;

		public VehiclesController(IAutobarnDatabase db) {
			this.db = db;
		}
		public IActionResult Index() {
			var vehicles = db.ListVehicles();
			return View(vehicles);
		}

		public IActionResult Details(string id) {
			var vehicle = db.FindVehicle(id);
			return View(vehicle);
		}

		[HttpGet]
		public IActionResult Advertise(string id) {
			var vehicleModel = db.FindModel(id);
			var dto = new VehicleDto() {
				ModelCode = vehicleModel.Code,
				ModelName = $"{vehicleModel.Manufacturer.Name} {vehicleModel.Name}"
			};
			return View(dto);
		}

		[HttpPost]
		public IActionResult Advertise(VehicleDto dto) {
			var existingVehicle = db.FindVehicle(dto.Registration);
			if (existingVehicle != default)
				ModelState.AddModelError(nameof(dto.Registration),
					"That registration is already listed in our database.");
			var vehicleModel = db.FindModel(dto.ModelCode);
			if (vehicleModel == default) {
				ModelState.AddModelError(nameof(dto.ModelCode),
					$"Sorry, {dto.ModelCode} is not a valid model code.");
			}
			if (!ModelState.IsValid) return View(dto);
			var vehicle = new Vehicle() {
				Registration = dto.Registration,
				Color = dto.Color,
				VehicleModel = vehicleModel,
				Year = dto.Year
			};
			db.CreateVehicle(vehicle);
			return RedirectToAction("Details", new { id = vehicle.Registration });
		}
	}
}

dotnet/Autobarn.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Autobarn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Autobarn</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manufacturers"
                               asp-action="Index">Makes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Models"
                               asp-action="Index">Models</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">
                                All
                                Cars
                            </a>
                        </li>
                        <li class="nav-item align-right">
                            <a class="nav-link text-dark" href="/hyperion/#/api">Hyperion</a>
                        </li>
                        <li class="nav-item align-right">
                            <a class="nav-link text-dark" href="/graphiql">GraphiQL</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="signalr-notifications"></div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            This is a sample app for <a href="https://dylanbeattie.net/">Dylan Beattie's</a> workshop <a href="https://urs.tl/dsnet">Distributed Systems with .NET</a>

        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/3.1.16/signalr.min.js"
            integrity="sha512-u9ogfmXtxjaWJfZRXKpspzaHvHIG8OHuGEeH4hihu73jX2Z/pBPQy+nLnz5Bc6T7jDbswEaGvIjSwyHTyk37Zw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>